const fs = require('fs');
const path = require('path');

// Files generated by the build process
const generatedFiles = [
  'web-components.min.js',
  'styles.min.css',
  'web-components.min.js.LICENSE.txt',
  'index.html'
];

console.log('Cleaning generated files...');

generatedFiles.forEach(file => {
  const filePath = path.join(__dirname, '..', file);
  
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
    console.log(`Removed ${file}`);
  } else {
    console.log(`File not found (skipped): ${file}`);
  }
});

console.log('Clean completed successfully!');